// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.sidetrack_job_status_enum */
enum SidetrackJobStatusEnum {
  scheduled = "scheduled",
  running = "running",
  cancelled = "cancelled",
  failed = "failed",
  retrying = "retrying",
  completed = "completed",
}

export default SidetrackJobStatusEnum;
