// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type SidetrackJobStatusEnum from "./SidetrackJobStatusEnum";

export type Id = string;

/** Represents the table public.sidetrack_jobs */
export default interface SidetrackJobs {
  attempted_at: Date | null;

  cancelled_at: Date | null;

  completed_at: Date | null;

  current_attempt: number;

  errors: unknown | null;

  failed_at: Date | null;

  id: Id;

  inserted_at: Date;

  max_attempts: number;

  payload: unknown;

  queue: string;

  scheduled_at: Date;

  status: SidetrackJobStatusEnum;
}

/** Represents the initializer for the table public.sidetrack_jobs */
export interface SidetrackJobsInitializer {
  attempted_at?: Date | null;

  cancelled_at?: Date | null;

  completed_at?: Date | null;

  current_attempt: number;

  errors?: unknown | null;

  failed_at?: Date | null;

  /** Default value: gen_random_uuid() */
  id?: Id;

  /** Default value: now() */
  inserted_at?: Date;

  max_attempts: number;

  payload: unknown;

  queue: string;

  /** Default value: now() */
  scheduled_at?: Date;

  status: SidetrackJobStatusEnum;
}

/** Represents the mutator for the table public.sidetrack_jobs */
export interface SidetrackJobsMutator {
  attempted_at?: Date | null;

  cancelled_at?: Date | null;

  completed_at?: Date | null;

  current_attempt?: number;

  errors?: unknown | null;

  failed_at?: Date | null;

  id?: Id;

  inserted_at?: Date;

  max_attempts?: number;

  payload?: unknown;

  queue?: string;

  scheduled_at?: Date;

  status?: SidetrackJobStatusEnum;
}
